### ISSUE TITLE
Windows vs Linux Jar File With Crux

### ISSUE THREAD

**Issue by pwhittin** [xtdb/xtdb#1023]
l've written a small sample application written in Clojure using lein.  The uberjar generated by lien executes correctly in Linux, but raises an exception in both Windows 7 and Windows 10.  In all cases the jar file is executed by Java 1.8.0 thusly:
```bash
java -jar demo.jar
```

Here's the Linux output:
```bash
/tmp=> java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~20.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
/tmp=> java -jar demo.jar 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Entity Count:  500 



Crux Query
==========
#{["Ivan"] ["Dmitry"] ["Yuri"] ["Antonina"] ["Slata"] ["Denis"]
  ["Sergei"] ["Maria"]}



Crux SQL Query
==============
({:name "Dmitry"}
 {:name "Antonina"}
 {:name "Denis"}
 {:name "Ivan"}
 {:name "Maria"})
```

Here's the Windows 7 output:
```bash
$ java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)

$ java -jar demo.jar
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Entity Count:  100



Crux Query
==========
#{["Ivan"] ["Dmitry"] ["Yuri"] ["Antonina"] ["Slata"] ["Denis"]
  ["Sergei"] ["Maria"]}



Crux SQL Query
==============
({:name "Denis"}
 {:name "Antonina"}
 {:name "Slata"}
 {:name "Yuri"}
 {:name "Maria"})

Exception in thread "crux.io.shutdown-hook-thread" java.nio.file.AccessDeniedException: C:\cygwin64\tmp\crux_rocksdb2946118858650382186\librocksdbjni-win64.dll
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at crux.io$fn__3396$fn__3397.invoke(io.clj:82)
        at crux.io.proxy$java.nio.file.SimpleFileVisitor$ff19274a.visitFile(Unknown Source)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at crux.io$delete_dir.invokeStatic(io.clj:92)
        at crux.io$create_tmpdir$fn__3404.invoke(io.clj:101)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:748)
```
Here's the project.clj file:
```clojure
(defproject my-crux-sql "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}
  :dependencies [[org.clojure/clojure "1.10.1"]
                 ;[juxt/crux-core "RELEASE"]
                 [juxt/crux-sql "RELEASE"]
                 [juxt/crux-rocksdb "RELEASE"]
                 ]
  :main ^:skip-aot my-crux-sql.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all
                       :jvm-opts ["-Dclojure.compiler.direct-linking=true"]}})
```
Here's the core.clj file:
```clojure
(ns my-crux-sql.core
  (:require [clojure.java.io :as io]
            [crux.api :as crux]
            crux.calcite
            )
  (:gen-class))

(defn uuid-gen []
  (java.util.UUID/randomUUID))

(defn start-rocks-node [storage-dir]
  (crux/start-node {:crux.node/topology                 '[crux.standalone/topology
                                                          crux.kv.rocksdb/kv-store
                                                          crux.calcite/module]
                    :crux.standalone/event-log-dir      (io/file storage-dir "event-log")
                    :crux.standalone/event-log-kv-store 'crux.kv.rocksdb/kv
                    :crux.kv/db-dir                     (str (io/file storage-dir "indexes"))}))


(defn random-person []
  {:crux.db/id (uuid-gen)
   :name       (rand-nth ["Ivan" "Slata" "Sergei" "Antonina" "Yuri" "Dmitry" "Maria" "Denis"])
   :last-name  (rand-nth ["Ivanov" "Petrov" "Sidorov" "Kovalev" "Kuznetsov" "Voronoi"])
   :sex        (rand-nth [:male :female])
   :age        (rand-int 100)
   :salary     (rand-int 100000)})

(defn query [node q]
  (with-open [conn (crux.calcite/jdbc-connection node)]
    (let [stmt (.createStatement conn)]
      (->> q (.executeQuery stmt) resultset-seq))))

(defn -main [& args]
  (try
    (let [node (start-rocks-node "db")]
      (doseq [p (take 100 (repeatedly random-person))]
        (let [tx (crux/submit-tx node [[:crux.tx/put p]])]
          (crux/await-tx node tx)))
      (println "\nEntity Count: " (count (crux/q (crux/db node) {:find  '[e]
                                                                 :where ['[e :name name]]})) "\n\n")
      (println "\nCrux Query\n==========")
      (clojure.pprint/pprint (crux/q (crux/db node) {:find  '[name]
                                                     :where ['[e :name name]]}))
      (println "\n")
      (crux/submit-tx node [[:crux.tx/put {:crux.db/id             :crux.sql.schema/person
                                           :crux.sql.table/name    "person"
                                           :crux.sql.table/query   '{:find  [?id ?name]
                                                                     :where [[?id :name ?name]]}
                                           :crux.sql.table/columns '{?id :keyword, ?name :varchar}}]])
      (println "\nCrux SQL Query\n==============")
      (clojure.pprint/pprint (take 5 (query node "SELECT PERSON.NAME FROM PERSON")))
      (println)
      (.close node))
    (catch Exception e
      (clojure.pprint/pprint e))))
```

**Comment by refset** [comment]
~~It looks like a permission issue whilst attempting to delete the RocksDB lock file, which is an important step within (.close node).~~

~~It could be worth trying our alternative RocksDB backend (using JNR) in your topology and see if it makes any difference: crux.kv.rocksdb.jnr/kv-store~~

In the meantime we'll try to reproduce this.

UPDATE:

On closer inspection the issue appears to be with the cleaning up of the temporary directory created by `crux.kv.rocksdb.loader` which uses `crux.io` to actually create and delete the directory: https://github.com/juxt/crux/blob/master/crux-core/src/crux/io.clj#L79-L103

Some brief research tells me that Windows handles deleting files and folders quite differently to Linux, so we need confirm how the existing method ought to work on Windows and perhaps consider a different approach (e.g. https://gist.github.com/edw/5128978)

Potentially insightful:
https://stackoverflow.com/questions/19935624/java-nio-file-files-deletepath-path-occasional-failure-to-recursively-delete
https://bugs.openjdk.java.net/browse/JDK-8215103

**Comment by danmason** [comment]
With regards to this problem, I belive simply having rocksdb as a dependency is enough to cause it. 

As jeremy mentioned, issue appears to come from the `crux.rocksdb.loader`: https://github.com/juxt/crux/blob/dfc4f68fa0c2468d547938a31cb96c1543007383/crux-rocksdb/src/crux/rocksdb/loader.clj

One can use `cio/create-temp-dir` just fine and delete regular folders, issue seems to come directly from trying to delete a `.dll` file.
