### ISSUE TITLE
Can't start with jdk 16

### ISSUE THREAD

**Issue by nivekuil** [xtdb/xtdb#1462]
Switched docker base image, built with juxt/pack, from openjdk:15 to openjdk:16, app exits on startup with
```
Exception in thread "crux-polling-tx-consumer" java.lang.ExceptionInInitializerError
at crux.cache.second_chance$random_entry.invokeStatic(second_chance.clj:16)
at crux.cache.second_chance$random_entry.invoke(second_chance.clj:15)
at crux.cache.second_chance$move_to_cooling_state.invokeStatic(second_chance.clj:79)
at crux.cache.second_chance$move_to_cooling_state.invoke(second_chance.clj:74)
at crux.cache.second_chance$resize_cache.invokeStatic(second_chance.clj:125)
at crux.cache.second_chance$resize_cache.invoke(second_chance.clj:121)
at crux.cache.second_chance.SecondChanceCache.computeIfAbsent(second_chance.clj:49)
at crux.cache$compute_if_absent.invokeStatic(cache.clj:7)
at crux.cache$compute_if_absent.invoke(cache.clj:6)
at crux.document_store.CachedDocumentStore$fn__65390.invoke(document_store.clj:58)
at clojure.lang.PersistentArrayMap.kvreduce(PersistentArrayMap.java:377)
at clojure.core$fn__8437.invokeStatic(core.clj:6845)
at clojure.core$fn__8437.invoke(core.clj:6830)
at clojure.core.protocols$fn__8167$G__8162__8176.invoke(protocols.clj:175)
at clojure.core$reduce_kv.invokeStatic(core.clj:6856)
at clojure.core$reduce_kv.invoke(core.clj:6847)
at crux.document_store.CachedDocumentStore._fetch_docs(document_store.clj:56)
at crux.fork.ForkedDocumentStore._fetch_docs(fork.clj:176)
at crux.db$fetch_docs.invokeStatic(db.clj:86)
at crux.db$fetch_docs.invoke(db.clj:79)
at crux.tx.InFlightTx.index_tx_events(tx.clj:293)
at crux.tx$index_tx_log$fn__13383$fn__13388.invoke(tx.clj:438)
at crux.tx$index_tx_log$fn__13383.invoke(tx.clj:429)
at crux.tx$index_tx_log.invokeStatic(tx.clj:421)
at crux.tx$index_tx_log.invoke(tx.clj:419)
at crux.tx$__GT_polling_tx_consumer$fn__13404.invoke(tx.clj:464)
at clojure.lang.AFn.run(AFn.java:22)
at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field transient volatile java.util.concurrent.ConcurrentHashMap$Node[] java.util.concurrent.ConcurrentHashMap.table accessible: module java.base does not "opens java.util.concurrent" to unnamed module @5a1ddc7c
at crux.cache.second_chance.ConcurrentHashMapTableAccess.<clinit>(ConcurrentHashMapTableAccess.java:34)
... 28 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient volatile java.util.concurrent.ConcurrentHashMap$Node[] java.util.concurrent.ConcurrentHashMap.table accessible: module java.base does not "opens java.util.concurrent" to unnamed module @5a1ddc7c
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
at crux.cache.second_chance.ConcurrentHashMapTableAccess.<clinit>(ConcurrentHashMapTableAccess.java:30)
... 28 more
2021-03-16T20:38:29.362Z 2fbdb3187939 INFO [org.eclipse.jetty.server.Server:360] - jetty-9.4.30.v20200611; built: 2020-06-11T12:34:51.929Z; git: 271836e4c1f4612f12b7bb13ef5a92a927634b0d; jvm 16+36-2231
2021-03-16T20:38:29.393Z 2fbdb3187939 INFO [org.eclipse.jetty.server.AbstractConnector:331] - Started ServerConnector@2d641e39{HTTP/1.1, (http/1.1)}{0.0.0.0:3000}
2021-03-16T20:38:29.395Z 2fbdb3187939 INFO [org.eclipse.jetty.server.Server:400] - Started @24111ms
2021-03-16T20:38:29.395Z 2fbdb3187939 INFO [crux.http-server:326] - HTTP server started on port:  3000
{:clojure.main/message
"Execution error (NoClassDefFoundError) at crux.cache.second-chance/random-entry (second_chance.clj:16).\nCould not initialize class crux.cache.second_chance.ConcurrentHashMapTableAccess\n",
:clojure.main/triage
{:clojure.error/class java.lang.NoClassDefFoundError,
:clojure.error/line 16,
:clojure.error/cause
"Could not initialize class crux.cache.second_chance.ConcurrentHashMapTableAccess",
:clojure.error/symbol crux.cache.second-chance/random-entry,
:clojure.error/source "second_chance.clj",
:clojure.error/phase :execution},
:clojure.main/trace
{:via
[{:type clojure.lang.ExceptionInfo,
	    :message "Error on key :app.crux/node when building system",
	    :data
	    {:reason :integrant.core/build-threw-exception,
	    :system
	    {:app.kv.s3/client
	    #object[software.amazon.awssdk.services.s3.DefaultS3AsyncClient 0x122e4e2f "software.amazon.awssdk.services.s3.DefaultS3AsyncClient@122e4e2f"],
	    :app.crux/s3
	    #object[app.crux$eval8724$fn__8726$fn__8728 0x6d3c81f4 "app.crux$eval8724$fn__8726$fn__8728@6d3c81f4"]},
	    :function
	    #object[clojure.lang.MultiFn 0x381c7573 "clojure.lang.MultiFn@381c7573"],
	    :key :app.crux/node,
	    :value
	    {:crux.http-server/server {:port 3000},
	    :crux.rocksdb/block-cache
	    {:crux/module crux.rocksdb/->lru-block-cache,
	    :cache-size 64000000},
	    :crux/index-store
	    {:kv-store
	    {:crux/module crux.rocksdb/->kv-store,
	    :db-dir "/tmp/crux/rocksdb-index",
	    :checkpointer
	    {:crux/module crux.checkpoint/->checkpointer,
	    :store
	    {:crux/module crux.s3.checkpoint/->cp-store,
	    :bucket "crux-checkpoint",
	    :configurator
	    #object[app.crux$eval8724$fn__8726$fn__8728 0x6d3c81f4 "app.crux$eval8724$fn__8726$fn__8728@6d3c81f4"]},
	    :approx-frequency "PT6H"},
	    :block-cache :crux.rocksdb/block-cache}},
	    :crux/tx-log
	    {:crux/module crux.kafka/->tx-log,
	    :kafka-config
	    {:bootstrap-servers
	    "redacted",
	    :properties-map
	    {"enable.idempotence" "false", "compression.type" "zstd"}},
	    :tx-topic-opts
	    {:topic-name "crux-tx-log",
	    :replication-factor 3,
	    :num-partitions 3,
	    :topic-config
	    {"min.insync.replicas" "2",
	    "message.timestamp.type" "CreateTime"}},
	    :poll-wait-duration "PT0.01S"},
	    :crux/document-store
	    {:crux/module app.crux.scylla/->document-store,
	    :keyspace "catablog_crux",
	    :addresses
	    ["redacted"],
	    :table "docs"}}},
	    :at [integrant.core$build_exception invokeStatic "core.cljc" 285]}
	    {:type java.lang.NoClassDefFoundError,
	    :message
	    "Could not initialize class crux.cache.second_chance.ConcurrentHashMapTableAccess",
	    :at
	    [crux.cache.second_chance$random_entry
	     invokeStatic
	     "second_chance.clj"
	     16]}],
:trace
[[crux.cache.second_chance$random_entry
  invokeStatic
  "second_chance.clj"
  16]
 [crux.cache.second_chance$random_entry
  invoke
  "second_chance.clj"
  15]
 [crux.cache.second_chance$move_to_cooling_state
  invokeStatic
  "second_chance.clj"
  79]
 [crux.cache.second_chance$move_to_cooling_state
  invoke
  "second_chance.clj"
  74]
 [crux.cache.second_chance$resize_cache
  invokeStatic
  "second_chance.clj"
  125]
 [crux.cache.second_chance$resize_cache
  invoke
  "second_chance.clj"
  121]
 [crux.cache.second_chance.SecondChanceCache
  evict
  "second_chance.clj"
  56]
 [crux.cache$evict invokeStatic "cache.clj" 10]
 [crux.cache$evict invoke "cache.clj" 9]
 [crux.document_store.CachedDocumentStore$iter__65394__65398$fn__65399
  invoke
  "document_store.clj"
  72]
 [clojure.lang.LazySeq sval "LazySeq.java" 42]
 [clojure.lang.LazySeq seq "LazySeq.java" 51]
 [clojure.lang.RT seq "RT.java" 535]
 [clojure.lang.LazilyPersistentVector
  create
  "LazilyPersistentVector.java"
  44]
 [clojure.core$vec invokeStatic "core.clj" 377]
 [clojure.core$vec invoke "core.clj" 367]
 [crux.document_store.CachedDocumentStore
  submit_docs
  "document_store.clj"
  70]
 [crux.node.CruxNode submit_tx "node.clj" 201]
 [app.crux$eval8734$fn__8735$fn__8736 invoke "crux.clj" 16]
 [app.crux$eval8734$fn__8735 invoke "crux.clj" 13]
 [clojure.lang.MultiFn invoke "MultiFn.java" 234]
 [integrant.core$try_build_action invokeStatic "core.cljc" 294]
 [integrant.core$try_build_action invoke "core.cljc" 293]
 [integrant.core$build_key invokeStatic "core.cljc" 302]
 [integrant.core$build_key invoke "core.cljc" 298]
 [clojure.core$partial$fn__5843 invoke "core.clj" 2639]
 [clojure.core.protocols$fn__8159 invokeStatic "protocols.clj" 168]
 [clojure.core.protocols$fn__8159 invoke "protocols.clj" 124]
 [clojure.core.protocols$fn__8114$G__8109__8123
  invoke
  "protocols.clj"
  19]
 [clojure.core.protocols$seq_reduce invokeStatic "protocols.clj" 31]
 [clojure.core.protocols$fn__8146 invokeStatic "protocols.clj" 75]
 [clojure.core.protocols$fn__8146 invoke "protocols.clj" 75]
 [clojure.core.protocols$fn__8088$G__8083__8101
  invoke
  "protocols.clj"
  13]
 [clojure.core$reduce invokeStatic "core.clj" 6828]
 [clojure.core$reduce invoke "core.clj" 6810]
 [integrant.core$build invokeStatic "core.cljc" 325]
 [integrant.core$build invoke "core.cljc" 305]
 [integrant.core$init invokeStatic "core.cljc" 431]
 [integrant.core$init invoke "core.cljc" 423]
 [integrant.core$init invokeStatic "core.cljc" 428]
 [integrant.core$init invoke "core.cljc" 423]
 [app.system$init invokeStatic "system.clj" 29]
 [app.system$init invoke "system.clj" 27]
 [app.system$_main invokeStatic "system.clj" 32]
 [app.system$_main doInvoke "system.clj" 31]
 [clojure.lang.RestFn invoke "RestFn.java" 397]
 [clojure.lang.AFn applyToHelper "AFn.java" 152]
 [clojure.lang.RestFn applyTo "RestFn.java" 132]
 [clojure.lang.Var applyTo "Var.java" 705]
 [clojure.core$apply invokeStatic "core.clj" 665]
 [clojure.main$main_opt invokeStatic "main.clj" 514]
 [clojure.main$main_opt invoke "main.clj" 510]
 [clojure.main$main invokeStatic "main.clj" 664]
 [clojure.main$main doInvoke "main.clj" 616]
 [clojure.lang.RestFn applyTo "RestFn.java" 137]
 [clojure.lang.Var applyTo "Var.java" 705]
 [clojure.main main "main.java" 40]],
:cause
"Could not initialize class crux.cache.second_chance.ConcurrentHashMapTableAccess"}}
Execution error (NoClassDefFoundError) at crux.cache.second-chance/random-entry (second_chance.clj:16).
Could not initialize class crux.cache.second_chance.ConcurrentHashMapTableAccess
```
Changing the base image back to openjdk:15 makes it work as expected

**Comment by jarohen** [comment]
Cheers @nivekuil :pray:

**Comment by jarohen** [comment]
It seems that in JDK 16 this kind of access was switched to deny by default (https://jdk.java.net/16/release-notes#JDK-8256299, https://openjdk.java.net/jeps/396). If you'd like to continue using JDK16, you can use either of the following VM opts as a workaround:
* `--add-opens java.base/java.util.concurrent=ALL-UNNAMED`
* `--illegal-access=permit` (or `--illegal-access=warn` to permit but show warnings)

In the meantime, we can check to see whether there are other options for the implementation of that cache :) 

(FYI @hraberg)

**Comment by jarohen** [comment]
(based on my recollection of a conversation with @hraberg - please correct me if I'm wrong!) 

We need access to this field because there's no way (via the public APIs) to reduce the size of this table when the cache has been emptied - in a pathological case, the cache's map ends up with a large empty table which it then has to scan through, causing a performance issue in Crux. I've made this a warning rather than allowing it to prevent startup though!

**Comment by jarohen** [comment]
Still doesn't work without the add-opens flag - idea is that it works but may not be as performant in certain cases
