### ISSUE TITLE
Help needed - attempting to start-http-server

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#2027]
Using `lein repl`:
```
user=> (dev)
Reflection warning, ring/adapter/jetty.clj:45:3 - call to org.eclipse.jetty.server.ServerConnector ctor can't be resolved.
:ok
dev=> (start-dev-system {:http-server? true :embed-kafka? true})

Execution error (TimeoutException) at (REPL:1).
Timeout expired while initializing transactional state in 60000ms.
```

Any ideas?

**Comment by refset** [comment]
hak Today at 2:59 PM
@jdt does normal `(dev/start)` work? check the options in `dev/dev-options` for required / useful options, not sure where that timeout is from, but could be ZK or Kafka I can imagine
1 reply
jdt < 1 minute ago
Thanks for the suggestion, but (dev) then (start) wouldn't work either, giving a huge number of warnings, including `15:11:23.031 [Controller-0-to-broker-0-send-thread] WARN  kafka.controller.RequestSendThread - [RequestSendThread controllerId=0] Controller 0 epoch 1 fails to send request` and `15:11:23.031 [Controller-0-to-broker-0-send-thread] WARN  kafka.controller.RequestSendThread - [RequestSendThread controllerId=0] Controller 0 epoch 1 fails to send request`I have managed to work around this by simply installing kafka and now have the http server running (yay!)

I followed:
https://docs.confluent.io/current/installation/installing_cp/deb-ubuntu.html#systemd-ubuntu-debian-install
and (from https://juxt.pro/crux/docs/user_guide.html#_http_server) ran:
```
user=> (require '[crux.api :as api])
nil
user=> (def storage-dir "dev-storage")
#'user/storage-dir
user=> (def local-node-options {:db-dir (str storage-dir "/data")
  #_=>                          :bootstrap-servers "localhost:9092"})
#'user/local-node-options
user=> (def local-node (api/start-local-node local-node-options))
#'user/local-node
user=> (require '[crux.http-server :as srv])
Reflection warning, ring/adapter/jetty.clj:45:3 - call to org.eclipse.jetty.server.ServerConnector ctor can't be resolved.
nil
user=> (def http-server-options {:server-port 3000})
#'user/http-server-options
user=> (def http-server (srv/start-http-server local-node http-server-options))
#'user/http-server
```
Result:
```
> curl http://localhost:3000/
{:crux.kv/kv-backend "crux.kv.rocksdb.RocksKv", :crux.kv/estimate-num-keys 0, :crux.kv/size 41822, :crux.zk/zk-active? true, :crux.tx-log/consumer-state nil
}
```

**Comment by hraberg** [comment]
I got similar warnings from Kafka trying to stop a newly seeded empty `dev-storage`, think I have seen this before, it's some timing issue when shutting down I think, and should be harmless. Though for me the system did work after initial start, checked via `(.status system)` in the REPL.

**Comment by megakorre** [comment]
I got errors trying to use `dev/start`

```
dev=> (start)
16:04:45.480 [nREPL-worker-0] ERROR k.zk.KafkaZkClient$CheckedEphemeral - Error while creating ephemeral at /brokers/ids/0, node already exists and owner '72071830639280128' does not match current session '72203083231002624'
16:04:45.484 [nREPL-worker-0] ERROR kafka.server.KafkaServer - [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown
org.apache.zookeeper.KeeperException$NodeExistsException: KeeperErrorCode = NodeExists
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:122)
	at kafka.zk.KafkaZkClient.checkedEphemeralCreate(KafkaZkClient.scala:1631)
	at kafka.zk.KafkaZkClient.registerBroker(KafkaZkClient.scala:87)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:257)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at crux.kafka.embedded$start_kafka_broker.invokeStatic(embedded.clj:36)
	at crux.kafka.embedded$start_kafka_broker.invoke(embedded.clj:34)
	at crux.kafka.embedded$start_embedded_kafka$fn__21344.invoke(embedded.clj:92)
	at crux.kafka.embedded$start_embedded_kafka.invokeStatic(embedded.clj:91)
	at crux.kafka.embedded$start_embedded_kafka.invoke(embedded.clj:73)
	at dev$start_dev_system.invokeStatic(dev.clj:41)
	at dev$start_dev_system.invoke(dev.clj:37)
	at dev$start$fn__22655.invoke(dev.clj:60)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.Var.alterRoot(Var.java:308)
	at clojure.core$alter_var_root.invokeStatic(core.clj:5510)
	at clojure.core$alter_var_root.doInvoke(core.clj:5505)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at dev$start.invokeStatic(dev.clj:60)
	at dev$start.invoke(dev.clj:59)
	at dev$eval22664.invokeStatic(form-init5315529417481683974.clj:1)
	at dev$eval22664.invoke(form-init5315529417481683974.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:7176)
	at clojure.lang.Compiler.eval(Compiler.java:7131)
	at clojure.core$eval.invokeStatic(core.clj:3214)
	at clojure.core$eval.invoke(core.clj:3210)
	at clojure.main$repl$read_eval_print__9068$fn__9071.invoke(main.clj:414)
	at clojure.main$repl$read_eval_print__9068.invoke(main.clj:414)
	at clojure.main$repl$fn__9077.invoke(main.clj:435)
	at clojure.main$repl.invokeStatic(main.clj:435)
	at clojure.main$repl.doInvoke(main.clj:345)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__1141.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1973)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1973)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__1186$fn__1189.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval
```

I cleared out `crux/dev-storage/*` and now `dev/start` works.

I also get a timeout when calling
```
dev=> (start-dev-system {:http-server? true :embed-kafka? true})
```
not sure how its intented to be called but this worked fine
```
dev=> (start-dev-system dev-options)
```
Edit: 
I read the implementation of `dev/start` and `(start-dev-system dev-options)` is what it calls so not that
supprised that it works
