### ISSUE TITLE
Upgrade to Arrow 5.0.0

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#2037]
https://arrow.apache.org/blog/2021/07/29/5.0.0-release/

Attempt at naive upgrade doesn't work, DenseUnionVector has changed and now inherits AbstractContainerVector, but not sure if this is the only problem.

**Comment by hraberg** [comment]
Upgrading to 5.0.0 and also removing our patched version of DenseUnionVector results in exceptions like these:

These happens in a lot of tests (different values, with value count at 0):
```
java.lang.IllegalArgumentException: Invalid parameters startIndex: 0, length: 1 for valueCount: 0
	at org.apache.arrow.util.Preconditions.checkArgument(Preconditions.java:413)
	at org.apache.arrow.vector.BitVector.splitAndTransferTo(BitVector.java:161)
	at org.apache.arrow.vector.BitVector$TransferImpl.splitAndTransfer(BitVector.java:591)
	at org.apache.arrow.vector.complex.DenseUnionVector$TransferImpl.splitAndTransfer(DenseUnionVector.java:1116)
	at core2.util$slice_root.invokeStatic(util.clj:304)
	at core2.util$slice_root.invokePrim(util.clj)
	at core2.util$slice_root.invokeStatic(util.clj:296)
	at core2.util$slice_root.invokePrim(util.clj)
	at core2.util$slice_root.invokeStatic(util.clj:293)
	at core2.util$slice_root.invoke(util.clj:291)
	at core2.indexer$snapshot_roots$fn__5806.invoke(indexer.clj:141)
```

These happens in `core2.datalog-test/test-joins`:
```
java.lang.IllegalArgumentException: should have as many children as in the schema: found 10 expected 11
	at org.apache.arrow.util.Preconditions.checkArgument(Preconditions.java:277)
	at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:127)
	at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:133)
	at org.apache.arrow.vector.VectorLoader.loadBuffers(VectorLoader.java:133)
	at org.apache.arrow.vector.VectorLoader.load(VectorLoader.java:84)
	at org.apache.arrow.vector.ipc.ArrowReader.loadRecordBatch(ArrowReader.java:214)
	at org.apache.arrow.vector.ipc.ArrowStreamReader.loadNextBatch(ArrowStreamReader.java:161)
	at core2.indexer.Indexer.indexTx(indexer.clj:362)
```

Can be reproduced by the following two documents (but with 8 as found and 9 as expected):
```
[[:put
  {:_id "you-only-live-twice",
   :film/director "lewis-gilbert",
   :film/bond "sean-connery",
   :film/box 756544419,
   :type "film",
   :film/name "You Only Live Twice",
   :film/year 1967}]
 [:put
  {:_id "akiko-wakabayashi",
   :type "person",
   :person/name "Akiko Wakabayashi",
   :person/role "Aki"}]]
```

**Comment by hraberg** [comment]
The second issue can be reproduced as this:
```
[[:put
  {:_id "you-only-live-twice",
   :type "film",
   :film/name "You Only Live Twice"}]
 [:put
  {:_id "akiko-wakabayashi",
   :type "person",
   :person/name "Akiko Wakabayashi"}]]
```
The root cause seems to be that `:film/name` and `:person/name` both gets turned into only `"name"` in the DenseUnionVector, while the schema has two fields called name, can be see on the `contentToTSVString` output:

```
tx-ops
{"document":{"_id":"you-only-live-twice","type":"film","name":"You Only Live Twice"}}
{"document":{"_id":"akiko-wakabayashi","type":"person","name":"Akiko Wakabayashi"}}
```

**Comment by hraberg** [comment]
Removing some types from our default DenseUnionVector manage to get rid of the first exception, but one then goes on to get this exception:

```
java.lang.NullPointerException: null
	at core2.DenseUnionUtil.writeTypeId(DenseUnionUtil.java:52)
	at core2.indexer$copy_duv_safe_BANG_.invokeStatic(indexer.clj:54)
	at core2.indexer$copy_duv_safe_BANG_.invoke(indexer.clj:51)
	at core2.indexer$copy_safe_BANG_.invokeStatic(indexer.clj:68)
	at core2.indexer$copy_safe_BANG_.invoke(indexer.clj:60)
	at core2.indexer.Indexer.indexTx(indexer.clj:408)
```

**Comment by jarohen** [comment]
@hraberg - I've rebuilt our fork on top of Arrow 5 and our tests seem fine. Haven't tried to remove our fork though...
