### ISSUE TITLE
No method in multimethod 'codegen-mono-call' for dispatch value: [:cast :utf8]

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#2222]
I don't know what it was that I ran specifically which may have triggered this error - I only noticed it in the console several hours after the fact:
```
| Unexpected exception sending query results, please report as a bug - you may need reconnect or restart XTDB
java.lang.IllegalArgumentException: No method in multimethod 'codegen-mono-call' for dispatch value: [:cast :utf8]
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at core2.expression$eval6061$fn__6063$iter__6093__6097$fn__6098.invoke(expression.clj:458)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:51)
	at clojure.lang.RT.seq(RT.java:535)
	at clojure.core$seq__5467.invokeStatic(core.clj:139)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
	at clojure.core.protocols$fn__8236.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8236.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$into.invokeStatic(core.clj:6958)
	at clojure.core$into.invoke(core.clj:6950)
	at core2.expression$eval6061$fn__6063.invoke(expression.clj:461)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at core2.expression$eval6175$fn__6177.invoke(expression.clj:543)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.expression$eval6013$fn__6015.invoke(expression.clj:387)
	at clojure.lang.MultiFn.invoke(MultiFn.java:234)
	at core2.operator.group_by$fn__10188.invokeStatic(group_by.clj:200)
	at core2.operator.group_by$fn__10188.invoke(group_by.clj:184)
	at core2.util$lru_memoize$fn__2759.invoke(util.clj:564)
	at core2.operator.group_by$reducing_agg_factory$reify$reify__10199.aggregate(group_by.clj:244)
	at core2.operator.group_by.GroupByCursor$fn$reify__10370.accept(group_by.clj:573)
	at core2.operator.project.ProjectCursor$reify__10538.accept(project.clj:85)
	at core2.operator.join.JoinCursor$fn$reify__11301.accept(join.clj:328)
	at core2.operator.project.ProjectCursor$reify__10538.accept(project.clj:85)
	at core2.operator.rename.RenameCursor$reify__11658.accept(rename.clj:41)
	at core2.coalesce.CoalescingCursor$reify__10676.accept(coalesce.clj:34)
	at core2.operator.scan.ScanCursor$next_block__10987$fn__10988.invoke(scan.clj:225)
	at core2.operator.scan.ScanCursor$next_block__10987.invoke(scan.clj:220)
	at core2.operator.scan.ScanCursor$live_chunk__11000.invoke(scan.clj:242)
	at core2.operator.scan.ScanCursor.tryAdvance(scan.clj:274)
	at core2.coalesce.CoalescingCursor.tryAdvance(coalesce.clj:24)
	at core2.util$and_also_close$reify__2738.tryAdvance(util.clj:490)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator.project.ProjectCursor.tryAdvance(project.clj:72)
	at core2.operator.join.JoinCursor$fn__11300.invoke(join.clj:320)
	at core2.operator.join.JoinCursor.tryAdvance(join.clj:317)
	at core2.operator.project.ProjectCursor.tryAdvance(project.clj:72)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)
	at core2.operator.group_by.GroupByCursor$fn__10369.invoke(group_by.clj:568)
	at core2.operator.group_by.GroupByCursor.tryAdvance(group_by.clj:567)
	at core2.operator.rename.RenameCursor.tryAdvance(rename.clj:31)
	at core2.operator.ResultCursor.tryAdvance(operator.clj:38)
	at core2.local_node.CursorResultSet.hasNext(local_node.clj:52)
	at core2.pgwire$cmd_send_query_result.invokeStatic(pgwire.clj:1309)
	at core2.pgwire$cmd_send_query_result.invoke(pgwire.clj:1283)
	at core2.pgwire$cmd_await_query_result.invokeStatic(pgwire.clj:1394)
	at core2.pgwire$cmd_await_query_result.invoke(pgwire.clj:1348)
	at core2.pgwire$cmd_exec_query.invokeStatic(pgwire.clj:1500)
	at core2.pgwire$cmd_exec_query.invoke(pgwire.clj:1418)
	at core2.pgwire$cmd_exec_stmt.invokeStatic(pgwire.clj:1634)
	at core2.pgwire$cmd_exec_stmt.invoke(pgwire.clj:1606)
	at core2.pgwire$cmd_simple_query.invokeStatic(pgwire.clj:1671)
	at core2.pgwire$cmd_simple_query.invoke(pgwire.clj:1666)
	at core2.pgwire$conn_loop.invokeStatic(pgwire.clj:1838)
	at core2.pgwire$conn_loop.invoke(pgwire.clj:1759)
	at core2.pgwire$connect$fn__18102.invoke(pgwire.clj:1903)
	at core2.pgwire$connect.invokeStatic(pgwire.clj:1901)
	at core2.pgwire$connect.invoke(pgwire.clj:1855)
	at core2.pgwire$accept_loop$fn__18116$fn__18117$fn__18118.invoke(pgwire.clj:1976)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jarohen** [comment]
fixed in https://github.com/xtdb/core2/commit/121bf4f914f13c77cffab6b0449f8874bd9162a3
