### ISSUE TITLE
API Takes content-hash

### ISSUE THREAD

**Issue by johantonelli** [xtdb/xtdb#237]
The current spec allows a hash in place of a document as an argument for the `put` transaction operation.

This results in this stacktrace

```
java.lang.RuntimeException: No reader function for tag crux/id
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:801)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:783)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:549)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.jav
a:757)
	at clojure.lang.EdnReader$VectorReader.invoke(EdnReader.java:672)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:757)
	at clojure.lang.EdnReader$VectorReader.invoke(EdnReader.java:672)
	at clojure.lang.EdnReader.read(EdnReader.java:145)
	at clojure.lang.EdnReader.read(EdnReader.java:111)
	at clojure.lang.EdnReader.readString(EdnReader.java:67)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	at clojure.edn$read_string.invokeStatic(edn.clj:37)
	at clojure.edn$read_string.invoke(edn.clj:37)
	at crux.http_server$body__GT_edn.invokeStatic(http_server.clj:39)
	at crux.http_server$body__GT_edn.invoke(http_server.clj:38)
	at crux.http_server$transact.invokeStatic(http_server.clj:222)
	at crux.http_server$transact.invoke(http_server.clj:221)
	at crux.http_server$handler.invokeStatic(http_server.clj:300)
	at crux.http_server$handler.invoke(http_server.clj:258)
	at clojure.core$partial$fn__5824.invoke(core.clj:2624)
	at ring.middleware.cors$handle_cors.invokeStatic(cors.cljc:178)
	at ring.midd
leware.cors$handle_cors.invoke(cors.cljc:167)
	at ring.middleware.cors$wrap_cors$fn__17941.invoke(cors.cljc:205)
	at ring.middleware.params$wrap_params$fn__17870.invoke(params.clj:67)
	at crux.http_server$wrap_exception_handling$fn__17961.invoke(http_server.clj:72)
```

**Comment by hraberg** [comment]
This bug should happen on `cas` as well, as its both first arguments also are documents.

Also worth noting that the spec as stands works for both submit and ingest, but this will force the spec to diverge into two, as the submit allows documents (but not hashes) and the ingest expects hashes (but would work for documents as well as the spec is written).

**Comment by johantonelli** [comment]
We've removed the exception being printed out, we did discover that the schema check is not being done by the remote api client which can cause internal 500s if http requests can't be serialised.
