### ISSUE TITLE
Exception in codec/index on latest snapshot

### ISSUE THREAD

**Issue by spacegangster** [xtdb/xtdb#258]
When launching crux-ui

```
10:19:08.989 ERROR crux.tx [crux.tx.event-log-consumer-thread]
Event log consumer threw exception, consumption has stopped:
java.lang.IllegalArgumentException: No implementation of method: :id->buffer of protocol: #'crux.codec/IdToBuffer found for class: java.lang.Long                    
        at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
        at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:575)
        at crux.codec$eval49261$fn__49262$G__49252__49269.invoke(codec.clj:46)
        at crux.codec$eval49472$fn__49473.invoke(codec.clj:313)
        at crux.codec$eval49224$fn__49236$G__49215__49241.invoke(codec.clj:42)
        at crux.index$index_doc$iter__50862__50868$fn__50869.invoke(index.clj:330)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:58)
        at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
        at clojure.core$chunk_next.invokeStatic(core.clj:708)
        at clojure.core.protocols$fn__8139.invokeStatic(protocols.clj:137)
        at clojure.core.protocols$fn__8139.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$reduce.invoke(core.clj:6810)
        at crux.index$index_doc.invokeStatic(index.clj:338)
        at crux.index$index_doc.invoke(index.clj:325)
        at crux.tx.KvIndexer.index_doc(tx.clj:181)
        at crux.tx$event_log_consumer_main_loop$fn__54680$fn__54681.invoke(tx.clj:341)                                                                               
        at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$reduce.invoke(core.clj:6810)
        at crux.tx$event_log_consumer_main_loop$fn__54680.invoke(tx.clj:337)
        at crux.tx$event_log_consumer_main_loop.invokeStatic(tx.clj:326)
        at crux.tx$event_log_consumer_main_loop.invoke(tx.clj:316)
        at crux.tx$start_event_log_consumer$fn__54694.invoke(tx.clj:365)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by spacegangster** [comment]
Same on 19-04-alpha-3.
Seems to be data related. I may have written some docs with int ids or keys. As if they got into event log, but now can't be processed by the indexer?

**Comment by spacegangster** [comment]
[broken-data.tar.gz](https://github.com/juxt/crux/files/3289592/broken-data.tar.gz)

**Comment by refset** [comment]
Could be good to improve the message here, not sure.

**Comment by refset** [comment]
Probably ought to have better specs on ingest

**Comment by refset** [comment]
#285 is related / pre-requisite
