### ISSUE TITLE
tx-test leads to Fatal Error

### ISSUE THREAD

**Issue by jonpither** [xtdb/xtdb#280]
This happens in `tx-test`, introduced in #265 

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f8e19c5c7ca, pid=22883, tid=7992
#
# JRE version: OpenJDK Runtime Environment (10.0.2+13) (build 10.0.2+13)
# Java VM: OpenJDK 64-Bit Server VM (10.0.2+13, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [liblwjgl_lmdb.so+0xe7ca]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" (or dumping to /home/jon/dev/juxt/crux/core.22883)
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Dfile.encoding=UTF-8 -Dclojure.compile.path=/home/jon/dev/juxt/crux/target/classes -Dcrux.version=19.06-1.1.1-alpha-SNAPSHOT -Dclojure.debug=false -Djava.library.path=/home/jon/dev/juxt/crux/target/native:/home/jon/dev/juxt/crux/target/native:/home/jon/dev/juxt/crux/target/native:/home/jon/dev/juxt/crux/target/native clojure.main -i /tmp/form-init12080172631445436664.clj

Host: Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz, 4 cores, 15G, Arch Linux
Time: Mon Jun 24 08:29:23 2019 BST elapsed time: 232 seconds (0d 0h 3m 52s)

---------------  T H R E A D  ---------------

Current thread (0x00007f8eaef35000):  JavaThread "crux.tx.event-log-consumer-thread" [_thread_in_native, id=7992, stack(0x00007f8e195d7000,0x00007f8e196d8000)]

Stack: [0x00007f8e195d7000,0x00007f8e196d8000],  sp=0x00007f8e196d6210,  free space=1020k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [liblwjgl_lmdb.so+0xe7ca]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 14177  org.lwjgl.util.lmdb.LMDB.nmdb_cursor_get(JJJI)I (0 bytes) @ 0x00007f8e9b83a51f [0x00007f8e9b83a460+0x00000000000000bf]
J 14622 c2 crux.kv.lmdb.LMDBKvIterator.seek(Ljava/lang/Object;)Ljava/lang/Object; (118 bytes) @ 0x00007f8e9b896bf8 [0x00007f8e9b896a60+0x0000000000000198]
J 13554 c2 crux.lru.CachedIterator.seek(Ljava/lang/Object;)Ljava/lang/Object; (126 bytes) @ 0x00007f8e9b7a658c [0x00007f8e9b7a63c0+0x00000000000001cc]
J 17398 c1 crux.moberg$seek_message.invokeStatic(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (280 bytes) @ 0x00007f8e95b639ec [0x00007f8e95b63180+0x000000000000086c]
J 17397 c1 crux.moberg$seek_message.invoke(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; (13 bytes) @ 0x00007f8e95b62c34 [0x00007f8e95b62bc0+0x0000000000000074]
J 17860 c1 crux.tx$event_log_consumer_main_loop$fn__10887.invoke()Ljava/lang/Object; (1113 bytes) @ 0x00007f8e94332604 [0x00007f8e94331640+0x0000000000000fc4]
j  crux.tx$event_log_consumer_main_loop.invokeStatic(Ljava/lang/Object;)Ljava/lang/Object;+344
j  crux.tx$event_log_consumer_main_loop.invoke(Ljava/lang/Object;)Ljava/lang/Object;+3
j  crux.tx$start_event_log_consumer$fn__10901.invoke()Ljava/lang/Object;+56
j  clojure.lang.AFn.run()V+1
J 16449 c1 java.lang.Thread.run()V java.base@10.0.2 (17 bytes) @ 0x00007f8e93fa621c [0x00007f8e93fa60e0+0x000000000000013c]
v  ~StubRoutines::call_stub
```

**Comment by jonpither** [comment]
Would seem to be `test-corrections-in-the-past-slowes-down-bitemp-144`. 

Also, I get other stacks from time to time for the same test - probably related

```
test-corrections-in-the-past-slowes-down-bitemp-144
13:25:52.023 [crux.tx.event-log-consumer-thread] ERROR crux.tx - Event log consumer threw exception, consumption has stopped:
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
	at org.lwjgl.util.lmdb.MDBVal.create(MDBVal.java:133)
	at crux.kv.lmdb.LMDBKvSnapshot.new_iterator(lmdb.clj:194)
	at crux.lru.CachedSnapshot.new_iterator(lru.clj:179)
	at crux.moberg$end_message_id_offset.invokeStatic(moberg.clj:80)
	at crux.moberg$end_message_id_offset.invokePrim(moberg.clj)
	at crux.tx$event_log_consumer_main_loop$fn__9062.invoke(tx.clj:284)
	at crux.tx$event_log_consumer_main_loop.invokeStatic(tx.clj:261)
	at crux.tx$event_log_consumer_main_loop.invoke(tx.clj:251)
	at crux.tx$start_event_log_consumer$fn__9076.invoke(tx.clj:300)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.lang.Thread.run(Thread.java:844)

lein test :only crux.tx-test/test-corrections-in-the-past-slowes-down-bitemp-144

ERROR in (test-corrections-in-the-past-slowes-down-bitemp-144) (tx.clj:371)
LMDB
Uncaught exception, not in assertion.
expected: nil
  actual: java.util.concurrent.TimeoutException: Timed out waiting for: #inst "2019-07-02T12:25:52.241-00:00" index has: #inst "1970-01-01T00:00:00.000-00:00"
 at crux.tx$await_tx_time.invokeStatic (tx.clj:371)
    crux.tx$await_tx_time.invoke (tx.clj:359)
    crux.bootstrap.CruxNode.sync (bootstrap.clj:115)
    crux.bootstrap.standalone.StandaloneSystem.sync (standalone.clj:66)
    crux.api$eval8463$fn__8478.invoke (api.clj:173)
    crux.api$eval8269$fn__8390$G__8252__8403.invoke (api.clj:43)
    crux.tx_test$fn__14167.invokeStatic (tx_test.clj:388)
    crux.tx_test/fn (tx_test.clj:380)
    clojure.test$test_var$fn__9707.invoke (test.clj:717)
    clojure.test$test_var.invokeStatic (test.clj:717)
    clojure.test$test_var.invoke (test.clj:708)
    clojure.test$test_vars$fn__9733$fn__9738.invoke (test.clj:735)
```

**Comment by hraberg** [comment]
Not 100% sure this is properly fixed or why my fix really works. But I removed the idle sleep from within the `with-open` block, and removed the usage of lazy-seqs, and the issue went away. That said, it might just still be a timing related issue, but which has now been even harder to trigger. We'll see if it resurfaces.

**Comment by hraberg** [comment]
Now crashes on CI with the new changes.

**Comment by hraberg** [comment]
If we decide to remove Moberg in favour of a log based on H2 or SQLite option, this card might be solved indirectly.

**Comment by hraberg** [comment]
Above solution related to and depending on #270.

**Comment by hraberg** [comment]
Spent some time trying to reproduce this again today, but haven't managed, as I never almost never see it on my slower laptop. Having spent time on this at several occasions, my preference is starting to lean towards simply getting rid of Moberg so we don't have to fix, tune and maintain it as well.

This would make standalone mode require `crux-jdbc` though, or we remove standalone mode, either implicitly, as a configured H2 or SQLite instance, or by explicitly requiring the setup, which is slightly more cumbersome, but somewhat easier to maintain.

**Comment by refset** [comment]
We should not forget to revert the disabled testing when this gets solved https://github.com/juxt/crux/commit/842c44f0aa485754bdf1c6186f7d2f17d3629ad1

**Comment by jarohen** [comment]
@jonpither @hraberg @refset this one still a problem? the LMDB tests seem to be back in

aware we've still got the #421 test commented out, if that's related

**Comment by jarohen** [comment]
LMDB is back in and these tests seem to be fine, closing.
