### ISSUE TITLE
IAE stops ingestion due to no method 'type->metadata-writer' for :decimal

### ISSUE THREAD

**Issue by refset** [xtdb/xtdb#3218]
Crash report (lightly edited) from @svilendobrev, running the latest 2.x version `f6afcc9`:

> In the course of submitting repeated batches of data, ~50 times for about 2 hours, this suddenly happened:
> 
>  09:57:41 | DEBUG xtdb.server | response error (class
>   clojure.lang.ExceptionInfo): 'Ingestion stopped:
>   java.lang.IllegalArgumentException: No method in multimethod
>    'type->metadata-writer' for dispatch value: :decimal'
> 
> ...and then it keeps spitting that so I have to stop + restart it.
> 
> Also, every time I stop it, it complains about:
> 
> 10:07:45 | ERROR o.apache.arrow.memory.BaseAllocator | Memory was
> leaked by query. Memory leaked: (14123776) Allocator(live-index)
> 0/14123776/98367488/9223372036854775807 (res/actual/peak/limit)
> 

Full stack trace:
```
09:58:49 | DEBUG xtdb.server | response error (class clojure.lang.ExceptionInfo): 'Ingestion stopped: java.lang.IllegalArgumentException: No method in multimethod 'type->metadata-writer' for dispatch value: :decimal'
clojure.lang.ExceptionInfo: Ingestion stopped: java.lang.IllegalArgumentException: No method in multimethod 'type->metadata-writer' for dispatch value: :decimal
	at xtdb.await$__GT_ingester_ex.invokeStatic(await.clj:17)
	at xtdb.await$__GT_ingester_ex.invoke(await.clj:16)
	at xtdb.await$await_tx_async$fn__29190.invoke(await.clj:30)
	at xtdb.await$await_tx_async.invokeStatic(await.clj:25)
	at xtdb.await$await_tx_async.invoke(await.clj:21)
	at xtdb.indexer.Indexer.awaitTxAsync(indexer.clj:687)
	at xtdb.node.impl.Node.openQueryAsync(impl.clj:86)
	at xtdb.api$eval3422$fn__3424.invoke(api.clj:188)
	at xtdb.protocols$eval865$fn__866$G__856__875.invoke(protocols.clj:4)
	at xtdb.server$eval23492$fn__23493$fn__23495.invoke(server.clj:240)
	at sieppari.interceptor$eval23005$fn__23006$fn__23007.invoke(interceptor.cljc:33)
	at sieppari.core$_try.invokeStatic(core.cljc:20)
	at sieppari.core$_try.invoke(core.cljc:17)
	at sieppari.core$enter.invokeStatic(core.cljc:62)
	at sieppari.core$enter.invoke(core.cljc:49)
	at sieppari.core$execute$fn__23211.invoke(core.cljc:125)
	at sieppari.core$execute.invokeStatic(core.cljc:123)
	at sieppari.core$execute.invoke(core.cljc:117)
	at reitit.interceptor.sieppari$reify__23220.execute(sieppari.clj:18)
	at reitit.http$ring_handler$fn__22278.invoke(http.cljc:165)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:436)
	at ring.adapter.jetty9.handlers.async$_doHandle.invokeStatic(async.clj:34)
	at ring.adapter.jetty9.handlers.async$_doHandle.invoke(async.clj:22)
	at ring.adapter.jetty9.handlers.AsyncProxyHandler.doHandle(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
	at ring.adapter.jetty9.handlers.AsyncProxyHandler.doScope(Unknown Source)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
	at org.eclipse.jetty.server.Server.handle(Server.java:563)
	at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:287)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.run(AdaptiveExecutionStrategy.java:199)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No method in multimethod 'type->metadata-writer' for dispatch value: :decimal
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at clojure.core$deref_future.invokeStatic(core.clj:2317)
	at clojure.core$deref.invokeStatic(core.clj:2337)
	at clojure.core$deref.invoke(core.clj:2323)
	at xtdb.indexer.live_index.LiveIndex.finish_chunk_BANG_(live_index.clj:356)
	at xtdb.indexer.live_index.LiveIndex$reify__29354.commit(live_index.clj:274)
	at xtdb.indexer.Indexer$fn__33931.invoke(indexer.clj:665)
	at xtdb.indexer.Indexer.indexTx(indexer.clj:603)
	at xtdb.log.watcher$watch_log_BANG_$reify__34168.acceptRecord(watcher.clj:53)
	at xtdb.log$tx_handler$fn__16589.invoke(log.clj:38)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$reduce.invoke(core.clj:6868)
	at xtdb.log$handle_polling_subscription$fn__16595.invoke(log.clj:52)
	at clojure.lang.AFn.run(AFn.java:22)
	... 1 common frames omitted
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'type->metadata-writer' for dispatch value: :decimal
	at clojure.lang.MultiFn.getFn(MultiFn.java:156)
	at clojure.lang.MultiFn.invoke(MultiFn.java:238)
	at xtdb.metadata$__GT_page_meta_wtr$__GT_nested_meta_writer$reify__16276.apply(metadata.clj:252)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
	at xtdb.metadata$__GT_page_meta_wtr$__GT_nested_meta_writer__16274.invoke(metadata.clj:248)
	at xtdb.metadata$__GT_page_meta_wtr$write_col_meta_BANG___16280$fn__16281.invoke(metadata.clj:259)
	at clojure.core$mapv$fn__8535.invoke(core.clj:6979)
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
	at clojure.core.protocols$fn__8230.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8230.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8178$G__8173__8191.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6886)
	at clojure.core$mapv.invokeStatic(core.clj:6970)
	at clojure.core$mapv.invoke(core.clj:6970)
	at xtdb.metadata$__GT_page_meta_wtr$write_col_meta_BANG___16280.invoke(metadata.clj:258)
	at xtdb.metadata$$reify__16292.writeMetadata(metadata.clj:285)
	at xtdb.trie$open_trie_writer$reify__16369.writeLeaf(trie.clj:140)
	at xtdb.trie$write_live_trie_node$write_node_BANG___16399.invoke(trie.clj:220)
	at xtdb.trie$write_live_trie_node.invokeStatic(trie.clj:222)
	at xtdb.trie$write_live_trie_node.invoke(trie.clj:199)
	at xtdb.trie$write_live_trie_BANG_$fn__16420.invoke(trie.clj:233)
	at xtdb.trie$write_live_trie_BANG_.invokeStatic(trie.clj:227)
	at xtdb.trie$write_live_trie_BANG_.invoke(trie.clj:224)
	at xtdb.indexer.live_index.LiveTable$fn__29332.invoke(live_index.clj:176)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by refset** [comment]
Closing this now as it's unlikely we'll be able to reproduce or validate the error given all the changes that have happened since (e2e decimal support, better ingestion-stopped error handling etc.). The new generative testing should smoke it out eventually if it's still lingering.
