### ISSUE TITLE
Race Condition Initialising Hash Implementation

### ISSUE THREAD

**Issue by hraberg** [xtdb/xtdb#486]
`crux.hash/id-hash` could be called from several threads at the same time when it first gets initialised, this can be fixed by putting the body of the initial version (which gets overridden) of the function in a `locking id-hash` macro. Alternatively, one could make this init eager. IIRC it was made lazy to avoid always logging hashing info just by loading some Crux namespaces.

**Comment by hraberg** [comment]
Issue looks like this, this var could temporarily stay unbound before being set to `nil` (on failure) or initialised properly if called from a different thread at the same time:

```
java.lang.IllegalStateException: Attempting to call unbound fn: #'crux.hash.jnr/openssl-id-hash-buffer
        at clojure.lang.Var$Unbound.throwArity(Var.java:45)
        at clojure.lang.AFn.invoke(AFn.java:36)
        at crux.hash$id_hash.invokeStatic(hash.clj:55)
        at crux.hash$id_hash.invoke(hash.clj:37)
        at crux.codec$id_function.invokeStatic(codec.clj:104)
```
